/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface CrowdfundingInterface extends Interface {
    getFunction(nameOrSignature: "EARLY_BIRD_BONUS_PERCENT" | "RATE" | "claim" | "claimed" | "closeEarly" | "closed" | "closedAt" | "contributions" | "coolingEnd" | "coolingPeriod" | "deadline" | "earlyBirdCount" | "endTime" | "ended" | "getProgress" | "goal" | "invest" | "investorIndex" | "investors" | "investorsCount" | "isSuccess" | "owner" | "ownerWithdrawn" | "refund" | "token" | "tokenAmountOf" | "totalRaised" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Claimed" | "Closed" | "Invested" | "Refunded" | "Withdrawn"): EventFragment;

    encodeFunctionData(functionFragment: 'EARLY_BIRD_BONUS_PERCENT', values?: undefined): string;
encodeFunctionData(functionFragment: 'RATE', values?: undefined): string;
encodeFunctionData(functionFragment: 'claim', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimed', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'closeEarly', values?: undefined): string;
encodeFunctionData(functionFragment: 'closed', values?: undefined): string;
encodeFunctionData(functionFragment: 'closedAt', values?: undefined): string;
encodeFunctionData(functionFragment: 'contributions', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'coolingEnd', values?: undefined): string;
encodeFunctionData(functionFragment: 'coolingPeriod', values?: undefined): string;
encodeFunctionData(functionFragment: 'deadline', values?: undefined): string;
encodeFunctionData(functionFragment: 'earlyBirdCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'endTime', values?: undefined): string;
encodeFunctionData(functionFragment: 'ended', values?: undefined): string;
encodeFunctionData(functionFragment: 'getProgress', values?: undefined): string;
encodeFunctionData(functionFragment: 'goal', values?: undefined): string;
encodeFunctionData(functionFragment: 'invest', values?: undefined): string;
encodeFunctionData(functionFragment: 'investorIndex', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'investors', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'investorsCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'isSuccess', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'ownerWithdrawn', values?: undefined): string;
encodeFunctionData(functionFragment: 'refund', values?: undefined): string;
encodeFunctionData(functionFragment: 'token', values?: undefined): string;
encodeFunctionData(functionFragment: 'tokenAmountOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'totalRaised', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdraw', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'EARLY_BIRD_BONUS_PERCENT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'RATE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'closeEarly', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'closed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'closedAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contributions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'coolingEnd', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'coolingPeriod', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deadline', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'earlyBirdCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'endTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ended', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProgress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'goal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'invest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'investorIndex', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'investors', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'investorsCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isSuccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ownerWithdrawn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenAmountOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalRaised', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace ClaimedEvent {
      export type InputTuple = [investor: AddressLike, tokenAmount: BigNumberish];
      export type OutputTuple = [investor: string, tokenAmount: bigint];
      export interface OutputObject {investor: string, tokenAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ClosedEvent {
      export type InputTuple = [closedAt: BigNumberish];
      export type OutputTuple = [closedAt: bigint];
      export interface OutputObject {closedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InvestedEvent {
      export type InputTuple = [investor: AddressLike, ethAmount: BigNumberish, order: BigNumberish];
      export type OutputTuple = [investor: string, ethAmount: bigint, order: bigint];
      export interface OutputObject {investor: string, ethAmount: bigint, order: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RefundedEvent {
      export type InputTuple = [investor: AddressLike, ethAmount: BigNumberish];
      export type OutputTuple = [investor: string, ethAmount: bigint];
      export interface OutputObject {investor: string, ethAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawnEvent {
      export type InputTuple = [owner: AddressLike, ethAmount: BigNumberish];
      export type OutputTuple = [owner: string, ethAmount: bigint];
      export interface OutputObject {owner: string, ethAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Crowdfunding extends BaseContract {
    
    connect(runner?: ContractRunner | null): Crowdfunding;
    waitForDeployment(): Promise<this>;

    interface: CrowdfundingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    EARLY_BIRD_BONUS_PERCENT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    RATE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    claim: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    claimed: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    closeEarly: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    closed: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    closedAt: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    contributions: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    coolingEnd: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    coolingPeriod: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    deadline: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    earlyBirdCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    endTime: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ended: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    getProgress: TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, bigint, boolean] & {raised: bigint, goalAmount: bigint, investorCount: bigint, deadlineTs: bigint, coolingEndTs: bigint, success: boolean }],
      'view'
    >
    

    
    goal: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    invest: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    investorIndex: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    investors: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    investorsCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    isSuccess: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    ownerWithdrawn: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    refund: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    tokenAmountOf: TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    totalRaised: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    withdraw: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'EARLY_BIRD_BONUS_PERCENT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'RATE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'claim'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimed'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'closeEarly'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'closed'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'closedAt'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'contributions'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'coolingEnd'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'coolingPeriod'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'deadline'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'earlyBirdCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'endTime'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ended'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getProgress'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, bigint, boolean] & {raised: bigint, goalAmount: bigint, investorCount: bigint, deadlineTs: bigint, coolingEndTs: bigint, success: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'goal'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'invest'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'investorIndex'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'investors'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'investorsCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isSuccess'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'ownerWithdrawn'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'refund'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'tokenAmountOf'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalRaised'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Claimed'): TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;
getEvent(key: 'Closed'): TypedContractEvent<ClosedEvent.InputTuple, ClosedEvent.OutputTuple, ClosedEvent.OutputObject>;
getEvent(key: 'Invested'): TypedContractEvent<InvestedEvent.InputTuple, InvestedEvent.OutputTuple, InvestedEvent.OutputObject>;
getEvent(key: 'Refunded'): TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;
getEvent(key: 'Withdrawn'): TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;

    filters: {
      
      'Claimed(address,uint256)': TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;
      Claimed: TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;
    

      'Closed(uint256)': TypedContractEvent<ClosedEvent.InputTuple, ClosedEvent.OutputTuple, ClosedEvent.OutputObject>;
      Closed: TypedContractEvent<ClosedEvent.InputTuple, ClosedEvent.OutputTuple, ClosedEvent.OutputObject>;
    

      'Invested(address,uint256,uint256)': TypedContractEvent<InvestedEvent.InputTuple, InvestedEvent.OutputTuple, InvestedEvent.OutputObject>;
      Invested: TypedContractEvent<InvestedEvent.InputTuple, InvestedEvent.OutputTuple, InvestedEvent.OutputObject>;
    

      'Refunded(address,uint256)': TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;
      Refunded: TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;
    

      'Withdrawn(address,uint256)': TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
      Withdrawn: TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
    
    };
  }